name: Feature
description: Product or engineering feature
title: "feat: "
labels: ["enhancement"]
body:
  - type: textarea
    id: outcome
    attributes:
      label: User outcome
      description: What customer problem does this solve?
    validations:
      required: true
  - type: textarea
    id: acceptance
    attributes:
      label: Acceptance criteria
    validations:
      required: true
